import type {Metadata} from "next";
import {Ubuntu, Roboto} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";


const ubuntu = Ubuntu({
    weight: '400',
    subsets: ['latin'],
})

const roboto = Roboto({
    weight: '500',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        {/*<head>*/}
        {/*    <link rel="icon" href="/favicon.ico" type="image/x-icon" />*/}
        {/*</head>*/}
        <body className={ubuntu.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
